export enum Scope {
  CONNECT_PROJECT_ADMIN = 'all:connect_project',
  CONNECT_PROJECT_ADMIN_ALIAS = 'all:project',

  PROJECTS_ALL = 'all:projects',
  PROJECTS_READ = 'read:projects',
  PROJECTS_WRITE = 'write:projects',
  PROJECTS_READ_USER_BILLING_ACCOUNTS = 'read:user-billing-accounts',
  PROJECTS_WRITE_PROJECTS_BILLING_ACCOUNTS = 'write:projects-billing-accounts',
  PROJECTS_READ_PROJECT_BILLING_ACCOUNT_DETAILS = 'read:project-billing-account-details',

  PROJECT_MEMBERS_ALL = 'all:project-members',
  PROJECT_MEMBERS_READ = 'read:project-members',
  PROJECT_MEMBERS_WRITE = 'write:project-members',

  PROJECT_INVITES_ALL = 'all:project-invites',
  PROJECT_INVITES_READ = 'read:project-invites',
  PROJECT_INVITES_WRITE = 'write:project-invites',

  CUSTOMER_PAYMENT_ALL = 'all:customer-payments',
  CUSTOMER_PAYMENT_READ = 'read:customer-payments',
  CUSTOMER_PAYMENT_WRITE = 'write:customer-payments',
}

export const M2M_SCOPES = {
  CONNECT_PROJECT_ADMIN: Scope.CONNECT_PROJECT_ADMIN,
  PROJECTS: {
    ALL: Scope.PROJECTS_ALL,
    READ: Scope.PROJECTS_READ,
    WRITE: Scope.PROJECTS_WRITE,
    READ_USER_BILLING_ACCOUNTS: Scope.PROJECTS_READ_USER_BILLING_ACCOUNTS,
    WRITE_PROJECTS_BILLING_ACCOUNTS:
      Scope.PROJECTS_WRITE_PROJECTS_BILLING_ACCOUNTS,
    READ_PROJECT_BILLING_ACCOUNT_DETAILS:
      Scope.PROJECTS_READ_PROJECT_BILLING_ACCOUNT_DETAILS,
  },
  PROJECT_MEMBERS: {
    ALL: Scope.PROJECT_MEMBERS_ALL,
    READ: Scope.PROJECT_MEMBERS_READ,
    WRITE: Scope.PROJECT_MEMBERS_WRITE,
  },
  PROJECT_INVITES: {
    ALL: Scope.PROJECT_INVITES_ALL,
    READ: Scope.PROJECT_INVITES_READ,
    WRITE: Scope.PROJECT_INVITES_WRITE,
  },
  CUSTOMER_PAYMENT: {
    ALL: Scope.CUSTOMER_PAYMENT_ALL,
    READ: Scope.CUSTOMER_PAYMENT_READ,
    WRITE: Scope.CUSTOMER_PAYMENT_WRITE,
  },
} as const;

export const ALL_PROJECT_RELATED_SCOPES: Scope[] = [
  Scope.PROJECTS_ALL,
  Scope.PROJECTS_READ,
  Scope.PROJECTS_WRITE,
  Scope.PROJECTS_READ_USER_BILLING_ACCOUNTS,
  Scope.PROJECTS_WRITE_PROJECTS_BILLING_ACCOUNTS,
  Scope.PROJECTS_READ_PROJECT_BILLING_ACCOUNT_DETAILS,
  Scope.PROJECT_MEMBERS_ALL,
  Scope.PROJECT_MEMBERS_READ,
  Scope.PROJECT_MEMBERS_WRITE,
  Scope.PROJECT_INVITES_ALL,
  Scope.PROJECT_INVITES_READ,
  Scope.PROJECT_INVITES_WRITE,
  Scope.CUSTOMER_PAYMENT_ALL,
  Scope.CUSTOMER_PAYMENT_READ,
  Scope.CUSTOMER_PAYMENT_WRITE,
];

export const SCOPE_HIERARCHY: Record<string, Scope[]> = {
  [Scope.PROJECTS_ALL]: [Scope.PROJECTS_READ, Scope.PROJECTS_WRITE],
  [Scope.PROJECT_MEMBERS_ALL]: [
    Scope.PROJECT_MEMBERS_READ,
    Scope.PROJECT_MEMBERS_WRITE,
  ],
  [Scope.PROJECT_INVITES_ALL]: [
    Scope.PROJECT_INVITES_READ,
    Scope.PROJECT_INVITES_WRITE,
  ],
  [Scope.CUSTOMER_PAYMENT_ALL]: [
    Scope.CUSTOMER_PAYMENT_READ,
    Scope.CUSTOMER_PAYMENT_WRITE,
  ],
  [Scope.CONNECT_PROJECT_ADMIN]: ALL_PROJECT_RELATED_SCOPES,
};

export const SCOPE_SYNONYMS: Record<string, Scope[]> = {
  [Scope.CONNECT_PROJECT_ADMIN_ALIAS]: [Scope.CONNECT_PROJECT_ADMIN],
};
